//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 07:29:29 AM CEST 
//


package de.chkal.backset.module.servlet.xml.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jcp.xmlns.xml.ns.javaee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WebFragment_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "web-fragment");
    private final static QName _WebApp_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "web-app");
    private final static QName _WebFragmentTypeSecurityConstraint_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "security-constraint");
    private final static QName _WebFragmentTypeWelcomeFileList_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "welcome-file-list");
    private final static QName _WebFragmentTypeErrorPage_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "error-page");
    private final static QName _WebFragmentTypeEjbLocalRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "ejb-local-ref");
    private final static QName _WebFragmentTypeJmsDestination_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "jms-destination");
    private final static QName _WebFragmentTypePersistenceContextRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "persistence-context-ref");
    private final static QName _WebFragmentTypeFilter_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "filter");
    private final static QName _WebFragmentTypeMessageDestinationRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "message-destination-ref");
    private final static QName _WebFragmentTypeServiceRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "service-ref");
    private final static QName _WebFragmentTypeJmsConnectionFactory_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "jms-connection-factory");
    private final static QName _WebFragmentTypePreDestroy_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "pre-destroy");
    private final static QName _WebFragmentTypeIcon_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "icon");
    private final static QName _WebFragmentTypeMimeMapping_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "mime-mapping");
    private final static QName _WebFragmentTypeLoginConfig_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "login-config");
    private final static QName _WebFragmentTypeDisplayName_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "display-name");
    private final static QName _WebFragmentTypeSecurityRole_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "security-role");
    private final static QName _WebFragmentTypeServlet_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "servlet");
    private final static QName _WebFragmentTypeFilterMapping_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "filter-mapping");
    private final static QName _WebFragmentTypeResourceEnvRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "resource-env-ref");
    private final static QName _WebFragmentTypeConnectionFactory_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "connection-factory");
    private final static QName _WebFragmentTypeName_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "name");
    private final static QName _WebFragmentTypeResourceRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "resource-ref");
    private final static QName _WebFragmentTypeDescription_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "description");
    private final static QName _WebFragmentTypeDistributable_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "distributable");
    private final static QName _WebFragmentTypeOrdering_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "ordering");
    private final static QName _WebFragmentTypeMailSession_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "mail-session");
    private final static QName _WebFragmentTypeListener_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "listener");
    private final static QName _WebFragmentTypePostConstruct_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "post-construct");
    private final static QName _WebFragmentTypeContextParam_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "context-param");
    private final static QName _WebFragmentTypeLocaleEncodingMappingList_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "locale-encoding-mapping-list");
    private final static QName _WebFragmentTypeJspConfig_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "jsp-config");
    private final static QName _WebFragmentTypeEjbRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "ejb-ref");
    private final static QName _WebFragmentTypeServletMapping_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "servlet-mapping");
    private final static QName _WebFragmentTypePersistenceUnitRef_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "persistence-unit-ref");
    private final static QName _WebFragmentTypeSessionConfig_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "session-config");
    private final static QName _WebFragmentTypeAdministeredObject_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "administered-object");
    private final static QName _WebFragmentTypeMessageDestination_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "message-destination");
    private final static QName _WebFragmentTypeEnvEntry_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "env-entry");
    private final static QName _WebFragmentTypeDataSource_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "data-source");
    private final static QName _WebAppTypeModuleName_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "module-name");
    private final static QName _WebAppTypeAbsoluteOrdering_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "absolute-ordering");
    private final static QName _WebAppTypeDenyUncoveredHttpMethods_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "deny-uncovered-http-methods");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jcp.xmlns.xml.ns.javaee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebAppType }
     * 
     */
    public WebAppType createWebAppType() {
        return new WebAppType();
    }

    /**
     * Create an instance of {@link WebFragmentType }
     * 
     */
    public WebFragmentType createWebFragmentType() {
        return new WebFragmentType();
    }

    /**
     * Create an instance of {@link TrueFalseType }
     * 
     */
    public TrueFalseType createTrueFalseType() {
        return new TrueFalseType();
    }

    /**
     * Create an instance of {@link LocalHomeType }
     * 
     */
    public LocalHomeType createLocalHomeType() {
        return new LocalHomeType();
    }

    /**
     * Create an instance of {@link FormLoginConfigType }
     * 
     */
    public FormLoginConfigType createFormLoginConfigType() {
        return new FormLoginConfigType();
    }

    /**
     * Create an instance of {@link SessionConfigType }
     * 
     */
    public SessionConfigType createSessionConfigType() {
        return new SessionConfigType();
    }

    /**
     * Create an instance of {@link AuthMethodType }
     * 
     */
    public AuthMethodType createAuthMethodType() {
        return new AuthMethodType();
    }

    /**
     * Create an instance of {@link UserDataConstraintType }
     * 
     */
    public UserDataConstraintType createUserDataConstraintType() {
        return new UserDataConstraintType();
    }

    /**
     * Create an instance of {@link JmsDestinationType }
     * 
     */
    public JmsDestinationType createJmsDestinationType() {
        return new JmsDestinationType();
    }

    /**
     * Create an instance of {@link HandlerChainType }
     * 
     */
    public HandlerChainType createHandlerChainType() {
        return new HandlerChainType();
    }

    /**
     * Create an instance of {@link CookieNameType }
     * 
     */
    public CookieNameType createCookieNameType() {
        return new CookieNameType();
    }

    /**
     * Create an instance of {@link RoleNameType }
     * 
     */
    public RoleNameType createRoleNameType() {
        return new RoleNameType();
    }

    /**
     * Create an instance of {@link IconType }
     * 
     */
    public IconType createIconType() {
        return new IconType();
    }

    /**
     * Create an instance of {@link TaglibType }
     * 
     */
    public TaglibType createTaglibType() {
        return new TaglibType();
    }

    /**
     * Create an instance of {@link SecurityRoleType }
     * 
     */
    public SecurityRoleType createSecurityRoleType() {
        return new SecurityRoleType();
    }

    /**
     * Create an instance of {@link EjbLocalRefType }
     * 
     */
    public EjbLocalRefType createEjbLocalRefType() {
        return new EjbLocalRefType();
    }

    /**
     * Create an instance of {@link XsdNMTOKENType }
     * 
     */
    public XsdNMTOKENType createXsdNMTOKENType() {
        return new XsdNMTOKENType();
    }

    /**
     * Create an instance of {@link TransportGuaranteeType }
     * 
     */
    public TransportGuaranteeType createTransportGuaranteeType() {
        return new TransportGuaranteeType();
    }

    /**
     * Create an instance of {@link ErrorCodeType }
     * 
     */
    public ErrorCodeType createErrorCodeType() {
        return new ErrorCodeType();
    }

    /**
     * Create an instance of {@link HandlerType }
     * 
     */
    public HandlerType createHandlerType() {
        return new HandlerType();
    }

    /**
     * Create an instance of {@link AddressingResponsesType }
     * 
     */
    public AddressingResponsesType createAddressingResponsesType() {
        return new AddressingResponsesType();
    }

    /**
     * Create an instance of {@link OrderingOthersType }
     * 
     */
    public OrderingOthersType createOrderingOthersType() {
        return new OrderingOthersType();
    }

    /**
     * Create an instance of {@link OrderingType }
     * 
     */
    public OrderingType createOrderingType() {
        return new OrderingType();
    }

    /**
     * Create an instance of {@link XsdBooleanType }
     * 
     */
    public XsdBooleanType createXsdBooleanType() {
        return new XsdBooleanType();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link AuthConstraintType }
     * 
     */
    public AuthConstraintType createAuthConstraintType() {
        return new AuthConstraintType();
    }

    /**
     * Create an instance of {@link PortComponentRefType }
     * 
     */
    public PortComponentRefType createPortComponentRefType() {
        return new PortComponentRefType();
    }

    /**
     * Create an instance of {@link MessageDestinationTypeType }
     * 
     */
    public MessageDestinationTypeType createMessageDestinationTypeType() {
        return new MessageDestinationTypeType();
    }

    /**
     * Create an instance of {@link CookiePathType }
     * 
     */
    public CookiePathType createCookiePathType() {
        return new CookiePathType();
    }

    /**
     * Create an instance of {@link JdbcUrlType }
     * 
     */
    public JdbcUrlType createJdbcUrlType() {
        return new JdbcUrlType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link MailSessionType }
     * 
     */
    public MailSessionType createMailSessionType() {
        return new MailSessionType();
    }

    /**
     * Create an instance of {@link PersistenceUnitRefType }
     * 
     */
    public PersistenceUnitRefType createPersistenceUnitRefType() {
        return new PersistenceUnitRefType();
    }

    /**
     * Create an instance of {@link XsdQNameType }
     * 
     */
    public XsdQNameType createXsdQNameType() {
        return new XsdQNameType();
    }

    /**
     * Create an instance of {@link MessageDestinationType }
     * 
     */
    public MessageDestinationType createMessageDestinationType() {
        return new MessageDestinationType();
    }

    /**
     * Create an instance of {@link JavaTypeType }
     * 
     */
    public JavaTypeType createJavaTypeType() {
        return new JavaTypeType();
    }

    /**
     * Create an instance of {@link ErrorPageType }
     * 
     */
    public ErrorPageType createErrorPageType() {
        return new ErrorPageType();
    }

    /**
     * Create an instance of {@link LocaleEncodingMappingListType }
     * 
     */
    public LocaleEncodingMappingListType createLocaleEncodingMappingListType() {
        return new LocaleEncodingMappingListType();
    }

    /**
     * Create an instance of {@link XsdAnyURIType }
     * 
     */
    public XsdAnyURIType createXsdAnyURIType() {
        return new XsdAnyURIType();
    }

    /**
     * Create an instance of {@link ServiceRefType }
     * 
     */
    public ServiceRefType createServiceRefType() {
        return new ServiceRefType();
    }

    /**
     * Create an instance of {@link NonEmptyStringType }
     * 
     */
    public NonEmptyStringType createNonEmptyStringType() {
        return new NonEmptyStringType();
    }

    /**
     * Create an instance of {@link RunAsType }
     * 
     */
    public RunAsType createRunAsType() {
        return new RunAsType();
    }

    /**
     * Create an instance of {@link UrlPatternType }
     * 
     */
    public UrlPatternType createUrlPatternType() {
        return new UrlPatternType();
    }

    /**
     * Create an instance of {@link HandlerChainsType }
     * 
     */
    public HandlerChainsType createHandlerChainsType() {
        return new HandlerChainsType();
    }

    /**
     * Create an instance of {@link AdministeredObjectType }
     * 
     */
    public AdministeredObjectType createAdministeredObjectType() {
        return new AdministeredObjectType();
    }

    /**
     * Create an instance of {@link PersistenceContextRefType }
     * 
     */
    public PersistenceContextRefType createPersistenceContextRefType() {
        return new PersistenceContextRefType();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link DisplayNameType }
     * 
     */
    public DisplayNameType createDisplayNameType() {
        return new DisplayNameType();
    }

    /**
     * Create an instance of {@link XsdIntegerType }
     * 
     */
    public XsdIntegerType createXsdIntegerType() {
        return new XsdIntegerType();
    }

    /**
     * Create an instance of {@link CookieDomainType }
     * 
     */
    public CookieDomainType createCookieDomainType() {
        return new CookieDomainType();
    }

    /**
     * Create an instance of {@link FullyQualifiedClassType }
     * 
     */
    public FullyQualifiedClassType createFullyQualifiedClassType() {
        return new FullyQualifiedClassType();
    }

    /**
     * Create an instance of {@link MessageDestinationUsageType }
     * 
     */
    public MessageDestinationUsageType createMessageDestinationUsageType() {
        return new MessageDestinationUsageType();
    }

    /**
     * Create an instance of {@link OrderingOrderingType }
     * 
     */
    public OrderingOrderingType createOrderingOrderingType() {
        return new OrderingOrderingType();
    }

    /**
     * Create an instance of {@link GenericBooleanType }
     * 
     */
    public GenericBooleanType createGenericBooleanType() {
        return new GenericBooleanType();
    }

    /**
     * Create an instance of {@link ServletMappingType }
     * 
     */
    public ServletMappingType createServletMappingType() {
        return new ServletMappingType();
    }

    /**
     * Create an instance of {@link FilterNameType }
     * 
     */
    public FilterNameType createFilterNameType() {
        return new FilterNameType();
    }

    /**
     * Create an instance of {@link EnvEntryTypeValuesType }
     * 
     */
    public EnvEntryTypeValuesType createEnvEntryTypeValuesType() {
        return new EnvEntryTypeValuesType();
    }

    /**
     * Create an instance of {@link WarPathType }
     * 
     */
    public WarPathType createWarPathType() {
        return new WarPathType();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link XsdNonNegativeIntegerType }
     * 
     */
    public XsdNonNegativeIntegerType createXsdNonNegativeIntegerType() {
        return new XsdNonNegativeIntegerType();
    }

    /**
     * Create an instance of {@link JspConfigType }
     * 
     */
    public JspConfigType createJspConfigType() {
        return new JspConfigType();
    }

    /**
     * Create an instance of {@link TrackingModeType }
     * 
     */
    public TrackingModeType createTrackingModeType() {
        return new TrackingModeType();
    }

    /**
     * Create an instance of {@link WelcomeFileListType }
     * 
     */
    public WelcomeFileListType createWelcomeFileListType() {
        return new WelcomeFileListType();
    }

    /**
     * Create an instance of {@link MessageDestinationLinkType }
     * 
     */
    public MessageDestinationLinkType createMessageDestinationLinkType() {
        return new MessageDestinationLinkType();
    }

    /**
     * Create an instance of {@link CookieConfigType }
     * 
     */
    public CookieConfigType createCookieConfigType() {
        return new CookieConfigType();
    }

    /**
     * Create an instance of {@link PersistenceContextSynchronizationType }
     * 
     */
    public PersistenceContextSynchronizationType createPersistenceContextSynchronizationType() {
        return new PersistenceContextSynchronizationType();
    }

    /**
     * Create an instance of {@link PersistenceContextTypeType }
     * 
     */
    public PersistenceContextTypeType createPersistenceContextTypeType() {
        return new PersistenceContextTypeType();
    }

    /**
     * Create an instance of {@link ListenerType }
     * 
     */
    public ListenerType createListenerType() {
        return new ListenerType();
    }

    /**
     * Create an instance of {@link ResAuthType }
     * 
     */
    public ResAuthType createResAuthType() {
        return new ResAuthType();
    }

    /**
     * Create an instance of {@link ConnectionFactoryResourceType }
     * 
     */
    public ConnectionFactoryResourceType createConnectionFactoryResourceType() {
        return new ConnectionFactoryResourceType();
    }

    /**
     * Create an instance of {@link InjectionTargetType }
     * 
     */
    public InjectionTargetType createInjectionTargetType() {
        return new InjectionTargetType();
    }

    /**
     * Create an instance of {@link MimeTypeType }
     * 
     */
    public MimeTypeType createMimeTypeType() {
        return new MimeTypeType();
    }

    /**
     * Create an instance of {@link TransactionSupportType }
     * 
     */
    public TransactionSupportType createTransactionSupportType() {
        return new TransactionSupportType();
    }

    /**
     * Create an instance of {@link ResSharingScopeType }
     * 
     */
    public ResSharingScopeType createResSharingScopeType() {
        return new ResSharingScopeType();
    }

    /**
     * Create an instance of {@link ResourceEnvRefType }
     * 
     */
    public ResourceEnvRefType createResourceEnvRefType() {
        return new ResourceEnvRefType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link JavaIdentifierType }
     * 
     */
    public JavaIdentifierType createJavaIdentifierType() {
        return new JavaIdentifierType();
    }

    /**
     * Create an instance of {@link HomeType }
     * 
     */
    public HomeType createHomeType() {
        return new HomeType();
    }

    /**
     * Create an instance of {@link JndiNameType }
     * 
     */
    public JndiNameType createJndiNameType() {
        return new JndiNameType();
    }

    /**
     * Create an instance of {@link EnvEntryType }
     * 
     */
    public EnvEntryType createEnvEntryType() {
        return new EnvEntryType();
    }

    /**
     * Create an instance of {@link MessageDestinationRefType }
     * 
     */
    public MessageDestinationRefType createMessageDestinationRefType() {
        return new MessageDestinationRefType();
    }

    /**
     * Create an instance of {@link EjbRefNameType }
     * 
     */
    public EjbRefNameType createEjbRefNameType() {
        return new EjbRefNameType();
    }

    /**
     * Create an instance of {@link JspPropertyGroupType }
     * 
     */
    public JspPropertyGroupType createJspPropertyGroupType() {
        return new JspPropertyGroupType();
    }

    /**
     * Create an instance of {@link AbsoluteOrderingType }
     * 
     */
    public AbsoluteOrderingType createAbsoluteOrderingType() {
        return new AbsoluteOrderingType();
    }

    /**
     * Create an instance of {@link EjbRefType }
     * 
     */
    public EjbRefType createEjbRefType() {
        return new EjbRefType();
    }

    /**
     * Create an instance of {@link MultipartConfigType }
     * 
     */
    public MultipartConfigType createMultipartConfigType() {
        return new MultipartConfigType();
    }

    /**
     * Create an instance of {@link LocaleEncodingMappingType }
     * 
     */
    public LocaleEncodingMappingType createLocaleEncodingMappingType() {
        return new LocaleEncodingMappingType();
    }

    /**
     * Create an instance of {@link SecurityConstraintType }
     * 
     */
    public SecurityConstraintType createSecurityConstraintType() {
        return new SecurityConstraintType();
    }

    /**
     * Create an instance of {@link JmsConnectionFactoryType }
     * 
     */
    public JmsConnectionFactoryType createJmsConnectionFactoryType() {
        return new JmsConnectionFactoryType();
    }

    /**
     * Create an instance of {@link MimeMappingType }
     * 
     */
    public MimeMappingType createMimeMappingType() {
        return new MimeMappingType();
    }

    /**
     * Create an instance of {@link EjbRefTypeType }
     * 
     */
    public EjbRefTypeType createEjbRefTypeType() {
        return new EjbRefTypeType();
    }

    /**
     * Create an instance of {@link EjbLinkType }
     * 
     */
    public EjbLinkType createEjbLinkType() {
        return new EjbLinkType();
    }

    /**
     * Create an instance of {@link WebResourceCollectionType }
     * 
     */
    public WebResourceCollectionType createWebResourceCollectionType() {
        return new WebResourceCollectionType();
    }

    /**
     * Create an instance of {@link LoginConfigType }
     * 
     */
    public LoginConfigType createLoginConfigType() {
        return new LoginConfigType();
    }

    /**
     * Create an instance of {@link LocalType }
     * 
     */
    public LocalType createLocalType() {
        return new LocalType();
    }

    /**
     * Create an instance of {@link ServletType }
     * 
     */
    public ServletType createServletType() {
        return new ServletType();
    }

    /**
     * Create an instance of {@link ResourceRefType }
     * 
     */
    public ResourceRefType createResourceRefType() {
        return new ResourceRefType();
    }

    /**
     * Create an instance of {@link LifecycleCallbackType }
     * 
     */
    public LifecycleCallbackType createLifecycleCallbackType() {
        return new LifecycleCallbackType();
    }

    /**
     * Create an instance of {@link RemoteType }
     * 
     */
    public RemoteType createRemoteType() {
        return new RemoteType();
    }

    /**
     * Create an instance of {@link JspFileType }
     * 
     */
    public JspFileType createJspFileType() {
        return new JspFileType();
    }

    /**
     * Create an instance of {@link SecurityRoleRefType }
     * 
     */
    public SecurityRoleRefType createSecurityRoleRefType() {
        return new SecurityRoleRefType();
    }

    /**
     * Create an instance of {@link CookieCommentType }
     * 
     */
    public CookieCommentType createCookieCommentType() {
        return new CookieCommentType();
    }

    /**
     * Create an instance of {@link ServletNameType }
     * 
     */
    public ServletNameType createServletNameType() {
        return new ServletNameType();
    }

    /**
     * Create an instance of {@link PathType }
     * 
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link DispatcherType }
     * 
     */
    public DispatcherType createDispatcherType() {
        return new DispatcherType();
    }

    /**
     * Create an instance of {@link AddressingType }
     * 
     */
    public AddressingType createAddressingType() {
        return new AddressingType();
    }

    /**
     * Create an instance of {@link XsdStringType }
     * 
     */
    public XsdStringType createXsdStringType() {
        return new XsdStringType();
    }

    /**
     * Create an instance of {@link ParamValueType }
     * 
     */
    public ParamValueType createParamValueType() {
        return new ParamValueType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link RespectBindingType }
     * 
     */
    public RespectBindingType createRespectBindingType() {
        return new RespectBindingType();
    }

    /**
     * Create an instance of {@link FilterMappingType }
     * 
     */
    public FilterMappingType createFilterMappingType() {
        return new FilterMappingType();
    }

    /**
     * Create an instance of {@link XsdPositiveIntegerType }
     * 
     */
    public XsdPositiveIntegerType createXsdPositiveIntegerType() {
        return new XsdPositiveIntegerType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebFragmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "web-fragment")
    public JAXBElement<WebFragmentType> createWebFragment(WebFragmentType value) {
        return new JAXBElement<WebFragmentType>(_WebFragment_QNAME, WebFragmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebAppType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "web-app")
    public JAXBElement<WebAppType> createWebApp(WebAppType value) {
        return new JAXBElement<WebAppType>(_WebApp_QNAME, WebAppType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityConstraintType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "security-constraint", scope = WebFragmentType.class)
    public JAXBElement<SecurityConstraintType> createWebFragmentTypeSecurityConstraint(SecurityConstraintType value) {
        return new JAXBElement<SecurityConstraintType>(_WebFragmentTypeSecurityConstraint_QNAME, SecurityConstraintType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WelcomeFileListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "welcome-file-list", scope = WebFragmentType.class)
    public JAXBElement<WelcomeFileListType> createWebFragmentTypeWelcomeFileList(WelcomeFileListType value) {
        return new JAXBElement<WelcomeFileListType>(_WebFragmentTypeWelcomeFileList_QNAME, WelcomeFileListType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorPageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "error-page", scope = WebFragmentType.class)
    public JAXBElement<ErrorPageType> createWebFragmentTypeErrorPage(ErrorPageType value) {
        return new JAXBElement<ErrorPageType>(_WebFragmentTypeErrorPage_QNAME, ErrorPageType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbLocalRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "ejb-local-ref", scope = WebFragmentType.class)
    public JAXBElement<EjbLocalRefType> createWebFragmentTypeEjbLocalRef(EjbLocalRefType value) {
        return new JAXBElement<EjbLocalRefType>(_WebFragmentTypeEjbLocalRef_QNAME, EjbLocalRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsDestinationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jms-destination", scope = WebFragmentType.class)
    public JAXBElement<JmsDestinationType> createWebFragmentTypeJmsDestination(JmsDestinationType value) {
        return new JAXBElement<JmsDestinationType>(_WebFragmentTypeJmsDestination_QNAME, JmsDestinationType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistenceContextRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "persistence-context-ref", scope = WebFragmentType.class)
    public JAXBElement<PersistenceContextRefType> createWebFragmentTypePersistenceContextRef(PersistenceContextRefType value) {
        return new JAXBElement<PersistenceContextRefType>(_WebFragmentTypePersistenceContextRef_QNAME, PersistenceContextRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "filter", scope = WebFragmentType.class)
    public JAXBElement<FilterType> createWebFragmentTypeFilter(FilterType value) {
        return new JAXBElement<FilterType>(_WebFragmentTypeFilter_QNAME, FilterType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageDestinationRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "message-destination-ref", scope = WebFragmentType.class)
    public JAXBElement<MessageDestinationRefType> createWebFragmentTypeMessageDestinationRef(MessageDestinationRefType value) {
        return new JAXBElement<MessageDestinationRefType>(_WebFragmentTypeMessageDestinationRef_QNAME, MessageDestinationRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "service-ref", scope = WebFragmentType.class)
    public JAXBElement<ServiceRefType> createWebFragmentTypeServiceRef(ServiceRefType value) {
        return new JAXBElement<ServiceRefType>(_WebFragmentTypeServiceRef_QNAME, ServiceRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsConnectionFactoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jms-connection-factory", scope = WebFragmentType.class)
    public JAXBElement<JmsConnectionFactoryType> createWebFragmentTypeJmsConnectionFactory(JmsConnectionFactoryType value) {
        return new JAXBElement<JmsConnectionFactoryType>(_WebFragmentTypeJmsConnectionFactory_QNAME, JmsConnectionFactoryType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "pre-destroy", scope = WebFragmentType.class)
    public JAXBElement<LifecycleCallbackType> createWebFragmentTypePreDestroy(LifecycleCallbackType value) {
        return new JAXBElement<LifecycleCallbackType>(_WebFragmentTypePreDestroy_QNAME, LifecycleCallbackType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "icon", scope = WebFragmentType.class)
    public JAXBElement<IconType> createWebFragmentTypeIcon(IconType value) {
        return new JAXBElement<IconType>(_WebFragmentTypeIcon_QNAME, IconType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MimeMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "mime-mapping", scope = WebFragmentType.class)
    public JAXBElement<MimeMappingType> createWebFragmentTypeMimeMapping(MimeMappingType value) {
        return new JAXBElement<MimeMappingType>(_WebFragmentTypeMimeMapping_QNAME, MimeMappingType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "login-config", scope = WebFragmentType.class)
    public JAXBElement<LoginConfigType> createWebFragmentTypeLoginConfig(LoginConfigType value) {
        return new JAXBElement<LoginConfigType>(_WebFragmentTypeLoginConfig_QNAME, LoginConfigType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisplayNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "display-name", scope = WebFragmentType.class)
    public JAXBElement<DisplayNameType> createWebFragmentTypeDisplayName(DisplayNameType value) {
        return new JAXBElement<DisplayNameType>(_WebFragmentTypeDisplayName_QNAME, DisplayNameType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "security-role", scope = WebFragmentType.class)
    public JAXBElement<SecurityRoleType> createWebFragmentTypeSecurityRole(SecurityRoleType value) {
        return new JAXBElement<SecurityRoleType>(_WebFragmentTypeSecurityRole_QNAME, SecurityRoleType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServletType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "servlet", scope = WebFragmentType.class)
    public JAXBElement<ServletType> createWebFragmentTypeServlet(ServletType value) {
        return new JAXBElement<ServletType>(_WebFragmentTypeServlet_QNAME, ServletType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "filter-mapping", scope = WebFragmentType.class)
    public JAXBElement<FilterMappingType> createWebFragmentTypeFilterMapping(FilterMappingType value) {
        return new JAXBElement<FilterMappingType>(_WebFragmentTypeFilterMapping_QNAME, FilterMappingType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceEnvRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "resource-env-ref", scope = WebFragmentType.class)
    public JAXBElement<ResourceEnvRefType> createWebFragmentTypeResourceEnvRef(ResourceEnvRefType value) {
        return new JAXBElement<ResourceEnvRefType>(_WebFragmentTypeResourceEnvRef_QNAME, ResourceEnvRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionFactoryResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "connection-factory", scope = WebFragmentType.class)
    public JAXBElement<ConnectionFactoryResourceType> createWebFragmentTypeConnectionFactory(ConnectionFactoryResourceType value) {
        return new JAXBElement<ConnectionFactoryResourceType>(_WebFragmentTypeConnectionFactory_QNAME, ConnectionFactoryResourceType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JavaIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "name", scope = WebFragmentType.class)
    public JAXBElement<JavaIdentifierType> createWebFragmentTypeName(JavaIdentifierType value) {
        return new JAXBElement<JavaIdentifierType>(_WebFragmentTypeName_QNAME, JavaIdentifierType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "resource-ref", scope = WebFragmentType.class)
    public JAXBElement<ResourceRefType> createWebFragmentTypeResourceRef(ResourceRefType value) {
        return new JAXBElement<ResourceRefType>(_WebFragmentTypeResourceRef_QNAME, ResourceRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "description", scope = WebFragmentType.class)
    public JAXBElement<DescriptionType> createWebFragmentTypeDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_WebFragmentTypeDescription_QNAME, DescriptionType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "distributable", scope = WebFragmentType.class)
    public JAXBElement<EmptyType> createWebFragmentTypeDistributable(EmptyType value) {
        return new JAXBElement<EmptyType>(_WebFragmentTypeDistributable_QNAME, EmptyType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "ordering", scope = WebFragmentType.class)
    public JAXBElement<OrderingType> createWebFragmentTypeOrdering(OrderingType value) {
        return new JAXBElement<OrderingType>(_WebFragmentTypeOrdering_QNAME, OrderingType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MailSessionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "mail-session", scope = WebFragmentType.class)
    public JAXBElement<MailSessionType> createWebFragmentTypeMailSession(MailSessionType value) {
        return new JAXBElement<MailSessionType>(_WebFragmentTypeMailSession_QNAME, MailSessionType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListenerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "listener", scope = WebFragmentType.class)
    public JAXBElement<ListenerType> createWebFragmentTypeListener(ListenerType value) {
        return new JAXBElement<ListenerType>(_WebFragmentTypeListener_QNAME, ListenerType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "post-construct", scope = WebFragmentType.class)
    public JAXBElement<LifecycleCallbackType> createWebFragmentTypePostConstruct(LifecycleCallbackType value) {
        return new JAXBElement<LifecycleCallbackType>(_WebFragmentTypePostConstruct_QNAME, LifecycleCallbackType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "context-param", scope = WebFragmentType.class)
    public JAXBElement<ParamValueType> createWebFragmentTypeContextParam(ParamValueType value) {
        return new JAXBElement<ParamValueType>(_WebFragmentTypeContextParam_QNAME, ParamValueType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocaleEncodingMappingListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "locale-encoding-mapping-list", scope = WebFragmentType.class)
    public JAXBElement<LocaleEncodingMappingListType> createWebFragmentTypeLocaleEncodingMappingList(LocaleEncodingMappingListType value) {
        return new JAXBElement<LocaleEncodingMappingListType>(_WebFragmentTypeLocaleEncodingMappingList_QNAME, LocaleEncodingMappingListType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JspConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jsp-config", scope = WebFragmentType.class)
    public JAXBElement<JspConfigType> createWebFragmentTypeJspConfig(JspConfigType value) {
        return new JAXBElement<JspConfigType>(_WebFragmentTypeJspConfig_QNAME, JspConfigType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "ejb-ref", scope = WebFragmentType.class)
    public JAXBElement<EjbRefType> createWebFragmentTypeEjbRef(EjbRefType value) {
        return new JAXBElement<EjbRefType>(_WebFragmentTypeEjbRef_QNAME, EjbRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServletMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "servlet-mapping", scope = WebFragmentType.class)
    public JAXBElement<ServletMappingType> createWebFragmentTypeServletMapping(ServletMappingType value) {
        return new JAXBElement<ServletMappingType>(_WebFragmentTypeServletMapping_QNAME, ServletMappingType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistenceUnitRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "persistence-unit-ref", scope = WebFragmentType.class)
    public JAXBElement<PersistenceUnitRefType> createWebFragmentTypePersistenceUnitRef(PersistenceUnitRefType value) {
        return new JAXBElement<PersistenceUnitRefType>(_WebFragmentTypePersistenceUnitRef_QNAME, PersistenceUnitRefType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "session-config", scope = WebFragmentType.class)
    public JAXBElement<SessionConfigType> createWebFragmentTypeSessionConfig(SessionConfigType value) {
        return new JAXBElement<SessionConfigType>(_WebFragmentTypeSessionConfig_QNAME, SessionConfigType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdministeredObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "administered-object", scope = WebFragmentType.class)
    public JAXBElement<AdministeredObjectType> createWebFragmentTypeAdministeredObject(AdministeredObjectType value) {
        return new JAXBElement<AdministeredObjectType>(_WebFragmentTypeAdministeredObject_QNAME, AdministeredObjectType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageDestinationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "message-destination", scope = WebFragmentType.class)
    public JAXBElement<MessageDestinationType> createWebFragmentTypeMessageDestination(MessageDestinationType value) {
        return new JAXBElement<MessageDestinationType>(_WebFragmentTypeMessageDestination_QNAME, MessageDestinationType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "env-entry", scope = WebFragmentType.class)
    public JAXBElement<EnvEntryType> createWebFragmentTypeEnvEntry(EnvEntryType value) {
        return new JAXBElement<EnvEntryType>(_WebFragmentTypeEnvEntry_QNAME, EnvEntryType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "data-source", scope = WebFragmentType.class)
    public JAXBElement<DataSourceType> createWebFragmentTypeDataSource(DataSourceType value) {
        return new JAXBElement<DataSourceType>(_WebFragmentTypeDataSource_QNAME, DataSourceType.class, WebFragmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityConstraintType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "security-constraint", scope = WebAppType.class)
    public JAXBElement<SecurityConstraintType> createWebAppTypeSecurityConstraint(SecurityConstraintType value) {
        return new JAXBElement<SecurityConstraintType>(_WebFragmentTypeSecurityConstraint_QNAME, SecurityConstraintType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WelcomeFileListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "welcome-file-list", scope = WebAppType.class)
    public JAXBElement<WelcomeFileListType> createWebAppTypeWelcomeFileList(WelcomeFileListType value) {
        return new JAXBElement<WelcomeFileListType>(_WebFragmentTypeWelcomeFileList_QNAME, WelcomeFileListType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorPageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "error-page", scope = WebAppType.class)
    public JAXBElement<ErrorPageType> createWebAppTypeErrorPage(ErrorPageType value) {
        return new JAXBElement<ErrorPageType>(_WebFragmentTypeErrorPage_QNAME, ErrorPageType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbLocalRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "ejb-local-ref", scope = WebAppType.class)
    public JAXBElement<EjbLocalRefType> createWebAppTypeEjbLocalRef(EjbLocalRefType value) {
        return new JAXBElement<EjbLocalRefType>(_WebFragmentTypeEjbLocalRef_QNAME, EjbLocalRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsDestinationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jms-destination", scope = WebAppType.class)
    public JAXBElement<JmsDestinationType> createWebAppTypeJmsDestination(JmsDestinationType value) {
        return new JAXBElement<JmsDestinationType>(_WebFragmentTypeJmsDestination_QNAME, JmsDestinationType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistenceContextRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "persistence-context-ref", scope = WebAppType.class)
    public JAXBElement<PersistenceContextRefType> createWebAppTypePersistenceContextRef(PersistenceContextRefType value) {
        return new JAXBElement<PersistenceContextRefType>(_WebFragmentTypePersistenceContextRef_QNAME, PersistenceContextRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "filter", scope = WebAppType.class)
    public JAXBElement<FilterType> createWebAppTypeFilter(FilterType value) {
        return new JAXBElement<FilterType>(_WebFragmentTypeFilter_QNAME, FilterType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "module-name", scope = WebAppType.class)
    public JAXBElement<String> createWebAppTypeModuleName(String value) {
        return new JAXBElement<String>(_WebAppTypeModuleName_QNAME, String.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageDestinationRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "message-destination-ref", scope = WebAppType.class)
    public JAXBElement<MessageDestinationRefType> createWebAppTypeMessageDestinationRef(MessageDestinationRefType value) {
        return new JAXBElement<MessageDestinationRefType>(_WebFragmentTypeMessageDestinationRef_QNAME, MessageDestinationRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "service-ref", scope = WebAppType.class)
    public JAXBElement<ServiceRefType> createWebAppTypeServiceRef(ServiceRefType value) {
        return new JAXBElement<ServiceRefType>(_WebFragmentTypeServiceRef_QNAME, ServiceRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsConnectionFactoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jms-connection-factory", scope = WebAppType.class)
    public JAXBElement<JmsConnectionFactoryType> createWebAppTypeJmsConnectionFactory(JmsConnectionFactoryType value) {
        return new JAXBElement<JmsConnectionFactoryType>(_WebFragmentTypeJmsConnectionFactory_QNAME, JmsConnectionFactoryType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "pre-destroy", scope = WebAppType.class)
    public JAXBElement<LifecycleCallbackType> createWebAppTypePreDestroy(LifecycleCallbackType value) {
        return new JAXBElement<LifecycleCallbackType>(_WebFragmentTypePreDestroy_QNAME, LifecycleCallbackType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "icon", scope = WebAppType.class)
    public JAXBElement<IconType> createWebAppTypeIcon(IconType value) {
        return new JAXBElement<IconType>(_WebFragmentTypeIcon_QNAME, IconType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MimeMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "mime-mapping", scope = WebAppType.class)
    public JAXBElement<MimeMappingType> createWebAppTypeMimeMapping(MimeMappingType value) {
        return new JAXBElement<MimeMappingType>(_WebFragmentTypeMimeMapping_QNAME, MimeMappingType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "login-config", scope = WebAppType.class)
    public JAXBElement<LoginConfigType> createWebAppTypeLoginConfig(LoginConfigType value) {
        return new JAXBElement<LoginConfigType>(_WebFragmentTypeLoginConfig_QNAME, LoginConfigType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisplayNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "display-name", scope = WebAppType.class)
    public JAXBElement<DisplayNameType> createWebAppTypeDisplayName(DisplayNameType value) {
        return new JAXBElement<DisplayNameType>(_WebFragmentTypeDisplayName_QNAME, DisplayNameType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "security-role", scope = WebAppType.class)
    public JAXBElement<SecurityRoleType> createWebAppTypeSecurityRole(SecurityRoleType value) {
        return new JAXBElement<SecurityRoleType>(_WebFragmentTypeSecurityRole_QNAME, SecurityRoleType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServletType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "servlet", scope = WebAppType.class)
    public JAXBElement<ServletType> createWebAppTypeServlet(ServletType value) {
        return new JAXBElement<ServletType>(_WebFragmentTypeServlet_QNAME, ServletType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbsoluteOrderingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "absolute-ordering", scope = WebAppType.class)
    public JAXBElement<AbsoluteOrderingType> createWebAppTypeAbsoluteOrdering(AbsoluteOrderingType value) {
        return new JAXBElement<AbsoluteOrderingType>(_WebAppTypeAbsoluteOrdering_QNAME, AbsoluteOrderingType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "filter-mapping", scope = WebAppType.class)
    public JAXBElement<FilterMappingType> createWebAppTypeFilterMapping(FilterMappingType value) {
        return new JAXBElement<FilterMappingType>(_WebFragmentTypeFilterMapping_QNAME, FilterMappingType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "deny-uncovered-http-methods", scope = WebAppType.class)
    public JAXBElement<EmptyType> createWebAppTypeDenyUncoveredHttpMethods(EmptyType value) {
        return new JAXBElement<EmptyType>(_WebAppTypeDenyUncoveredHttpMethods_QNAME, EmptyType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceEnvRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "resource-env-ref", scope = WebAppType.class)
    public JAXBElement<ResourceEnvRefType> createWebAppTypeResourceEnvRef(ResourceEnvRefType value) {
        return new JAXBElement<ResourceEnvRefType>(_WebFragmentTypeResourceEnvRef_QNAME, ResourceEnvRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionFactoryResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "connection-factory", scope = WebAppType.class)
    public JAXBElement<ConnectionFactoryResourceType> createWebAppTypeConnectionFactory(ConnectionFactoryResourceType value) {
        return new JAXBElement<ConnectionFactoryResourceType>(_WebFragmentTypeConnectionFactory_QNAME, ConnectionFactoryResourceType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "resource-ref", scope = WebAppType.class)
    public JAXBElement<ResourceRefType> createWebAppTypeResourceRef(ResourceRefType value) {
        return new JAXBElement<ResourceRefType>(_WebFragmentTypeResourceRef_QNAME, ResourceRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "description", scope = WebAppType.class)
    public JAXBElement<DescriptionType> createWebAppTypeDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_WebFragmentTypeDescription_QNAME, DescriptionType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "distributable", scope = WebAppType.class)
    public JAXBElement<EmptyType> createWebAppTypeDistributable(EmptyType value) {
        return new JAXBElement<EmptyType>(_WebFragmentTypeDistributable_QNAME, EmptyType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MailSessionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "mail-session", scope = WebAppType.class)
    public JAXBElement<MailSessionType> createWebAppTypeMailSession(MailSessionType value) {
        return new JAXBElement<MailSessionType>(_WebFragmentTypeMailSession_QNAME, MailSessionType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListenerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "listener", scope = WebAppType.class)
    public JAXBElement<ListenerType> createWebAppTypeListener(ListenerType value) {
        return new JAXBElement<ListenerType>(_WebFragmentTypeListener_QNAME, ListenerType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "post-construct", scope = WebAppType.class)
    public JAXBElement<LifecycleCallbackType> createWebAppTypePostConstruct(LifecycleCallbackType value) {
        return new JAXBElement<LifecycleCallbackType>(_WebFragmentTypePostConstruct_QNAME, LifecycleCallbackType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "context-param", scope = WebAppType.class)
    public JAXBElement<ParamValueType> createWebAppTypeContextParam(ParamValueType value) {
        return new JAXBElement<ParamValueType>(_WebFragmentTypeContextParam_QNAME, ParamValueType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocaleEncodingMappingListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "locale-encoding-mapping-list", scope = WebAppType.class)
    public JAXBElement<LocaleEncodingMappingListType> createWebAppTypeLocaleEncodingMappingList(LocaleEncodingMappingListType value) {
        return new JAXBElement<LocaleEncodingMappingListType>(_WebFragmentTypeLocaleEncodingMappingList_QNAME, LocaleEncodingMappingListType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JspConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "jsp-config", scope = WebAppType.class)
    public JAXBElement<JspConfigType> createWebAppTypeJspConfig(JspConfigType value) {
        return new JAXBElement<JspConfigType>(_WebFragmentTypeJspConfig_QNAME, JspConfigType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EjbRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "ejb-ref", scope = WebAppType.class)
    public JAXBElement<EjbRefType> createWebAppTypeEjbRef(EjbRefType value) {
        return new JAXBElement<EjbRefType>(_WebFragmentTypeEjbRef_QNAME, EjbRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServletMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "servlet-mapping", scope = WebAppType.class)
    public JAXBElement<ServletMappingType> createWebAppTypeServletMapping(ServletMappingType value) {
        return new JAXBElement<ServletMappingType>(_WebFragmentTypeServletMapping_QNAME, ServletMappingType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistenceUnitRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "persistence-unit-ref", scope = WebAppType.class)
    public JAXBElement<PersistenceUnitRefType> createWebAppTypePersistenceUnitRef(PersistenceUnitRefType value) {
        return new JAXBElement<PersistenceUnitRefType>(_WebFragmentTypePersistenceUnitRef_QNAME, PersistenceUnitRefType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "session-config", scope = WebAppType.class)
    public JAXBElement<SessionConfigType> createWebAppTypeSessionConfig(SessionConfigType value) {
        return new JAXBElement<SessionConfigType>(_WebFragmentTypeSessionConfig_QNAME, SessionConfigType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdministeredObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "administered-object", scope = WebAppType.class)
    public JAXBElement<AdministeredObjectType> createWebAppTypeAdministeredObject(AdministeredObjectType value) {
        return new JAXBElement<AdministeredObjectType>(_WebFragmentTypeAdministeredObject_QNAME, AdministeredObjectType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageDestinationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "message-destination", scope = WebAppType.class)
    public JAXBElement<MessageDestinationType> createWebAppTypeMessageDestination(MessageDestinationType value) {
        return new JAXBElement<MessageDestinationType>(_WebFragmentTypeMessageDestination_QNAME, MessageDestinationType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "env-entry", scope = WebAppType.class)
    public JAXBElement<EnvEntryType> createWebAppTypeEnvEntry(EnvEntryType value) {
        return new JAXBElement<EnvEntryType>(_WebFragmentTypeEnvEntry_QNAME, EnvEntryType.class, WebAppType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "data-source", scope = WebAppType.class)
    public JAXBElement<DataSourceType> createWebAppTypeDataSource(DataSourceType value) {
        return new JAXBElement<DataSourceType>(_WebFragmentTypeDataSource_QNAME, DataSourceType.class, WebAppType.class, value);
    }

}
