//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 07:29:29 AM CEST 
//


package de.chkal.backset.module.servlet.xml.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *         Please see section 8.2.2 of the specification for details.
 *         
 *       
 * 
 * <p>Java class for orderingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="after" type="{http://xmlns.jcp.org/xml/ns/javaee}ordering-orderingType" minOccurs="0"/>
 *         &lt;element name="before" type="{http://xmlns.jcp.org/xml/ns/javaee}ordering-orderingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderingType", propOrder = {
    "after",
    "before"
})
public class OrderingType {

    protected OrderingOrderingType after;
    protected OrderingOrderingType before;

    /**
     * Gets the value of the after property.
     * 
     * @return
     *     possible object is
     *     {@link OrderingOrderingType }
     *     
     */
    public OrderingOrderingType getAfter() {
        return after;
    }

    /**
     * Sets the value of the after property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderingOrderingType }
     *     
     */
    public void setAfter(OrderingOrderingType value) {
        this.after = value;
    }

    /**
     * Gets the value of the before property.
     * 
     * @return
     *     possible object is
     *     {@link OrderingOrderingType }
     *     
     */
    public OrderingOrderingType getBefore() {
        return before;
    }

    /**
     * Sets the value of the before property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderingOrderingType }
     *     
     */
    public void setBefore(OrderingOrderingType value) {
        this.before = value;
    }

}
